### ISSUE TITLE
Simple program not working

### ISSUE THREAD

**Issue by styleex** [go-ldap/ldap#137]
go 1.9
windows server 2012r2

I run the simplest program many times and get a whole kaleidoscope of different errors.

Program (adapted from readme):
```
package main

import (
	"gopkg.in/ldap.v2"
	"fmt"
	"log"
)

func main() {
	bindusername := "ivan@mydomain.com"
	bindpassword := "1"

	l, err := ldap.Dial("tcp", fmt.Sprintf("%s:%d", "win-uuaqs9o87gn.mydomain.com", 389))
	if err != nil {
		log.Fatal(err)
	}
	defer l.Close()

	l.Start()

	err = l.Bind(bindusername, bindpassword)
	if err != nil {
		log.Fatal(err)
	}

	// Search for the given username
	searchRequest := ldap.NewSearchRequest(
		"dc=mydomain,dc=com",
		ldap.ScopeWholeSubtree, ldap.NeverDerefAliases, 0, 0, false,
		"(ObjectClass=user)",
		[]string{"dn", "memberOf"},
		nil,
	)

	sr, err := l.Search(searchRequest)
	if err != nil {
		log.Fatalf("Search request: %s", err)
	}

	if len(sr.Entries) < 1 {
		log.Fatal("User does not exist or too many entries returned")
	}

	log.Println(sr.Entries[0].GetAttributeValue("memberOf"))
}
\
```
And I get the following errors:

Error1:
```
2017/10/19 22:01:39 CN=Гости,CN=Builtin,DC=mydomain,DC=com
2017/10/19 22:01:39 Received unexpected message 2, true
LDAP Response: (Universal, Constructed, Sequence and Sequence of) Len=487 "<nil>"
 Message ID: (Universal, Primitive, Integer) Len=1 "2"
 Search Result Entry: (Application, Constructed, 0x04) Len=480 "<nil>"
  Object Name: (Universal, Primitive, Octet String) Len=57 "CN=Администратор,CN=Users,DC=mydomain,DC=com"
  Attributes: (Universal, Constructed, Sequence and Sequence of) Len=417 "<nil>"
   Attribute: (Universal, Constructed, Sequence and Sequence of) Len=413 "<nil>"
    Attribute Name: (Universal, Primitive, Octet String) Len=8 "memberOf"
    Attribute Values: (Universal, Constructed, Set and Set OF) Len=399 "<nil>"
     Attribute Value: (Universal, Primitive, Octet String) Len=104 "CN=Владельцы-создатели групповой политики,CN=Users,DC=mydomain,DC=com"
     Attribute Value: (Universal, Primitive, Octet String) Len=72 "CN=Администраторы домена,CN=Users,DC=mydomain,DC=com"
     Attribute Value: (Universal, Primitive, Octet String) Len=82 "CN=Администраторы предприятия,CN=Users,DC=mydomain,DC=com"
     Attribute Value: (Universal, Primitive, Octet String) Len=70 "CN=Администраторы схемы,CN=Users,DC=mydomain,DC=com"
     Attribute Value: (Universal, Primitive, Octet String) Len=61 "CN=Администраторы,CN=Builtin,DC=mydomain,DC=com"
2017/10/19 22:01:39 ldap: recovered panic in processMessages: send on closed channel
panic: send on closed channel [recovered]
	panic: close of closed channel

goroutine 12 [running]:
gopkg.in/ldap%2ev2.(*Conn).processMessages.func1(0xc4200763c0)
	/usr/share/gocode/src/gopkg.in/ldap.v2/conn.go:343 +0x242
panic(0x5334c0, 0x575360)
	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
gopkg.in/ldap%2ev2.(*Conn).processMessages(0xc4200763c0)
	/usr/share/gocode/src/gopkg.in/ldap.v2/conn.go:350 +0x148
created by gopkg.in/ldap%2ev2.(*Conn).Start
	/usr/share/gocode/src/gopkg.in/ldap.v2/conn.go:157 +0x61
exit status 2
```

Error 2:
```
2017/10/19 22:05:08 Search request: LDAP Result Code 200 "": ldap: response channel closed
exit status 1
```

Error 3:
```
2017/10/19 22:05:31 CN=Владельцы-создатели групповой политики,CN=Users,DC=mydomain,DC=com
2017/10/19 22:05:31 ldap: recovered panic in processMessages: send on closed channel
panic: send on closed channel [recovered]
	panic: close of closed channel

goroutine 10 [running]:
gopkg.in/ldap%2ev2.(*Conn).processMessages.func1(0xc4200763c0)
	/usr/share/gocode/src/gopkg.in/ldap.v2/conn.go:343 +0x242
panic(0x5334c0, 0x575360)
	/usr/lib/go-1.9/src/runtime/panic.go:491 +0x283
gopkg.in/ldap%2ev2.(*Conn).processMessages(0xc4200763c0)
	/usr/share/gocode/src/gopkg.in/ldap.v2/conn.go:350 +0x148
created by gopkg.in/ldap%2ev2.(*Conn).Start
	/usr/share/gocode/src/gopkg.in/ldap.v2/conn.go:157 +0x61
exit status 2
```

Error 4:

```
2017/10/19 22:06:06 ldap: recovered panic in reader: interface conversion: interface {} is string, not int64
2017/10/19 22:06:06 Search request: LDAP Result Code 200 "": ldap: response channel closed
exit status 1
```

Error 5:

```
2017/10/19 22:06:53 ldap: recovered panic in reader: interface conversion: interface {} is string, not int64
2017/10/19 22:06:53 Search request: unable to read LDAP response packet: expected to read 125 bytes, read 276
exit status 1
```

**Comment by johnweldon** [comment]
Unable to reproduce with OpenLDAP - can you still reproduce this with AD?
