### ISSUE TITLE
bug: panic on ldap: conn is nil, expected net.Conn

### ISSUE THREAD

**Issue by greenpau** [go-ldap/ldap#357]
Trace:

```
2022/01/28 17:51:50 ldap: recovered panic in reader: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x169e5c0]

goroutine 97 [running]:
github.com/go-ldap/ldap/v3.(*Conn).Close(0xc00049de80)
        github.com/go-ldap/ldap/v3@v3.4.1/conn.go:274 +0x100
github.com/go-ldap/ldap/v3.(*Conn).reader.func1(0xc0010efede, 0xc00049de80)
        github.com/go-ldap/ldap/v3@v3.4.1/conn.go:541 +0x65
panic(0x1999460, 0x3162b50)
        runtime/panic.go:965 +0x1b9
bufio.(*Reader).Read(0xc000334e40, 0xc0004a64f6, 0x1, 0x1, 0xc001089b48, 0x4511ac, 0x1)
        bufio/bufio.go:227 +0x1fe
io.ReadAtLeast(0x265e480, 0xc000334e40, 0xc0004a64f6, 0x1, 0x1, 0x1, 0x40f4c8, 0xc000ee3bf8, 0xc3f0012f)
        io/io.go:328 +0x87
io.ReadFull(...)
        io/io.go:347
github.com/go-asn1-ber/asn1-ber.readByte(0x265e480, 0xc000334e40, 0xc0000927e0, 0xc000ee3bf8, 0xc000ee3c18)
        github.com/go-asn1-ber/asn1-ber@v1.5.1/util.go:7 +0x88
github.com/go-asn1-ber/asn1-ber.readIdentifier(0x265e480, 0xc000334e40, 0x4b3, 0x4b79e5, 0x1a31e60, 0x0, 0xc0004370e0)
        github.com/go-asn1-ber/asn1-ber@v1.5.1/identifier.go:14 +0x4d
github.com/go-asn1-ber/asn1-ber.readHeader(0x265e480, 0xc000334e40, 0xc000ee3d98, 0x64d854, 0xc000098024, 0x11375ba, 0x712de3, 0xc000c757a0)
        github.com/go-asn1-ber/asn1-ber@v1.5.1/header.go:15 +0x3f
github.com/go-asn1-ber/asn1-ber.readPacket(0x265e480, 0xc000334e40, 0x1000, 0xc0010f7000, 0x0, 0xc000001a08)
        github.com/go-asn1-ber/asn1-ber@v1.5.1/ber.go:287 +0x50
github.com/go-asn1-ber/asn1-ber.ReadPacket(...)
        github.com/go-asn1-ber/asn1-ber@v1.5.1/ber.go:210
github.com/go-ldap/ldap/v3.(*Conn).reader(0xc00049de80)
        github.com/go-ldap/ldap/v3@v3.4.1/conn.go:551 +0x116
created by github.com/go-ldap/ldap/v3.(*Conn).Start
        github.com/go-ldap/ldap/v3@v3.4.1/conn.go:248 +0x5c
```

The error I am getting is `ldap: conn is nil, expected net.Conn`.

The code:

```
        conn, err := sa.dial(server)
        if err != nil {
            sa.logger.Warn(
                "LDAP connection failed",
                zap.String("server", server.Address),
                zap.Error(err),
            )
            continue
        }
        defer conn.Close()
```

https://github.com/greenpau/go-authcrunch/blob/9d6a012e925239d3e4c16400dff105b3d68fa65d/pkg/authn/backends/ldap/authenticator.go#L267-L272

**Comment by vetinari** [comment]
The code in `dial()` has at least 2 cases where it returns `nil, nil`:
https://github.com/greenpau/go-authcrunch/blob/9d6a012e925239d3e4c16400dff105b3d68fa65d/pkg/authn/backends/ldap/authenticator.go#L493
https://github.com/greenpau/go-authcrunch/blob/9d6a012e925239d3e4c16400dff105b3d68fa65d/pkg/authn/backends/ldap/authenticator.go#L504

**Comment by greenpau** [comment]
> The code in dial() has at least 2 cases where it returns nil, nil:

@vetinari , thank you for taking a look 👍 The problem is in my code.
