### ISSUE TITLE
errors retrieving 'memberOf' attribute

### ISSUE THREAD

**Issue by ogxm** [go-ldap/ldap#363]
LDAP server is MS AD.
'ldapsearch' successfully obtains and lists 'memberOf' attribute values. go-ldap/v3 fails, as illustrated below.
Furthermore, all runs end up with failure to successfully close connections.

runtime diagnostics output along with Debugging log

doSearch:
	filter: (&(objectCategory=user)(objectClass=user)(sn=lastname))
	attribs: [memberOf]
2022/03/23 10:51:36 Finished message 1
LDAP Request: (Universal, Constructed, Sequence and Sequence of) Len=152 "<nil>"
 MessageID: (Universal, Primitive, Integer) Len=1 "1"
 Search Request: (Application, Constructed, 0x03) Len=109 "<nil>"
  Base DN: (Universal, Primitive, Octet String) Len=20 "dc=ad,dc=example,dc=com"
  Scope: (Universal, Primitive, Enumerated) Len=1 "2"
  Deref Aliases: (Universal, Primitive, Enumerated) Len=1 "0"
  Size Limit: (Universal, Primitive, Integer) Len=1 "0"
  Time Limit: (Universal, Primitive, Integer) Len=1 "0"
  Types Only: (Universal, Primitive, Boolean) Len=1 "false"
  And: (Context, Constructed, 0x00) Len=58 "<nil>"
   Equality Match: (Context, Constructed, 0x03) Len=22 "<nil>"
    Attribute: (Universal, Primitive, Octet String) Len=14 "objectCategory"
    Condition: (Universal, Primitive, Octet String) Len=4 "user"
   Equality Match: (Context, Constructed, 0x03) Len=19 "<nil>"
    Attribute: (Universal, Primitive, Octet String) Len=11 "objectClass"
    Condition: (Universal, Primitive, Octet String) Len=4 "user"
   Equality Match: (Context, Constructed, 0x03) Len=11 "<nil>"
    Attribute: (Universal, Primitive, Octet String) Len=2 "sn"
    Condition: (Universal, Primitive, Octet String) Len=5 "lastname"
  Attributes: (Universal, Constructed, Sequence and Sequence of) Len=10 "<nil>"
   Attribute: (Universal, Primitive, Octet String) Len=8 "memberOf"
 Controls: (Context, Constructed, 0x00) Len=36 "<nil>"
  Control: (Universal, Constructed, Sequence and Sequence of) Len=34 "<nil>"
   Control Type (Paging): (Universal, Primitive, Octet String) Len=22 "1.2.840.113556.1.4.319"
   Control Value (Paging): (Universal, Primitive, Octet String) Len=8 "<nil>"
    Search Control Value: (Universal, Constructed, Sequence and Sequence of) Len=6 "<nil>"
     Paging Size: (Universal, Primitive, Integer) Len=2 "256"
     Cookie: (Universal, Primitive, Octet String) Len=0 "[]"
2022/03/23 10:51:36 flags&startTLS = 0
2022/03/23 10:51:36 1: returning
2022/03/23 10:51:36 1: waiting for response
2022/03/23 10:51:36 Sending message 1
2022/03/23 10:51:36 reader error: expected to read 65 bytes, read 85
2022/03/23 10:51:36 Sending quit message and waiting for confirmation
2022/03/23 10:51:36 Shutting down - quit message received
2022/03/23 10:51:36 Closing channel for MessageID 1
2022/03/23 10:51:36 Closing network connection
2022/03/23 10:51:36 1: got response 0x0
2022/03/23 10:51:36 ldap: recovered panic in processMessages: send on closed channel
panic: send on closed channel [recovered]
	panic: close of closed channel

goroutine 22 [running]:
github.com/go-ldap/ldap/v3.(*Conn).processMessages.func1(0xc0003da280)
	/IdeaProjects/GO/src/github.com/go-ldap/ldap/v3/conn.go:458 +0x2e7
panic(0x12b6f80, 0x136cd60)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/go-ldap/ldap/v3.(*Conn).processMessages(0xc0003da280)
	/IdeaProjects/GO/src/github.com/go-ldap/ldap/v3/conn.go:464 +0x126
created by github.com/go-ldap/ldap/v3.(*Conn).Start
	/IdeaProjects/GO/src/github.com/go-ldap/ldap/v3/conn.go:249 +0x7e

**Comment by vetinari** [comment]
can you share the code that produces this issue? without any context it's not possible to reproduce

**Comment by ogxm** [comment]
[doSearch.go.txt](https://github.com/go-ldap/ldap/files/8343662/doSearch.go.txt)

**Comment by ogxm** [comment]
@vetinari it has been attached

**Comment by ogxm** [comment]
Excellent. That was it. It wasn't clear from examples I had reviewed.
