### ISSUE TITLE
cannot decode encoded paging control

### ISSUE THREAD

**Issue by vetinari** [go-ldap/ldap#82]
The following code fails with a panic:
```go
package ldap_test

import (
    "testing"
    "gopkg.in/ldap.v2"
)

func TestControlPagingEncodeDecode(t *testing.T) {
    c := ldap.NewControlPaging(100)
    packet := c.Encode()
    _ = ldap.DecodeControl(packet)
}
```

```
--- FAIL: TestControlPagingEncodeDecode (0.00s)
panic: interface conversion: interface is uint64, not int64 [recovered]
        panic: interface conversion: interface is uint64, not int64

goroutine 5 [running]:
panic(0x7d5760, 0xc820056780)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
testing.tRunner.func1(0xc8200841b0)
        /usr/local/go/src/testing/testing.go:467 +0x192
panic(0x7d5760, 0xc820056780)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
gopkg.in/ldap%2ev2.DecodeControl(0xc820018310, 0x0, 0x0)
        /home/hanno/go/src/gopkg.in/ldap.v2/control.go:283 +0x682
_/home/hanno/git/go-ldap_test.TestControlPagingEncodeDecode(0xc8200841b0)
        /home/hanno/git/go-ldap/control_test.go:11 +0x5b
testing.tRunner(0xc8200841b0, 0xa3fbb8)
        /usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:582 +0x892
exit status 2
FAIL    _/home/hanno/git/go-ldap        0.007s
```
The PagingSize value is encoded as uint64, but decoded as int64

**Comment by liggitt** [comment]
thanks for the report... fixed in vetinari
